{{- if .Spec.Enabled "rbac" }}{{ if not .Spec.DisableAuthProxy}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Spec.Name }}-proxy-role
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Spec.Name }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Spec.Name }}-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Spec.Namespace }}
---
{{ end }}{{ end }}
