{{- if .Spec.Development.GenerateCert }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ .Spec.Namespace }}
data:
  tls.key: {{ .Status.CertKey }}
  tls.crt: {{ .Status.CertCA }}
---
{{ end }}
