{{- if .Spec.Enabled "prometheus" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Spec.Namespace }}
  name: controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      control-plane: controller-manager
---
{{ end }}
